# Generated by Django 3.2.16 on 2025-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_subscription_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['price', 'price'], name='services_su_price_ea0e35_idx'),
        ),
    ]
